export const FETCH_PHONES_REQUEST = 'FETCH_PHONES_REQUEST - [All Phones]';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS - [All Phones]';

export const FETCH_PHONEBYID_REQUEST = 'FETCH_PHONES_REQUEST_BYID - [Phone By ID]';
export const FETCH_PHONEBYID_SUCCESS = 'FETCH_PHONES_SUCCESS_BYID - [Phone By ID]';
